#注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
#  instance:
#    perferIpAddress : true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8&amp;useSSL=false
    username: root
    password: a141617
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  config:
    key: saas-hrm
    ttl: 3600000

ai:
  appId: 20440932
  apiKey: yOD7OkQR989zXQZgYRI8t11v
  secretKey: naYNjHKHdvGEWGY6lklDjQi9ek6L5YIb
  imageType: BASE64
  groupId: wanghe

ac:
  appId: 1400389421
  appKey: 711329e2f7f3d89fbb315b048f4f3c64
  templateId: 645155
  smsSign: 皊行天

qr:
  url: http://localhost:8080/#/facelogin

yrpc:
  zookeeper:
    address: 193.112.100.103:2181
    root-path: /yRpc
    session-time-out: 10000
  netty:
    port: 8989
    host: 127.0.0.1